# To disable an addon, remove the '#' at the beginning of the line
DisabledAddons:
#- AutoJoin # This addon makes players auto-join the match/match pool
#- MaxSkills # This addon gives players in active matches max skills
#- NoDeathDrops # This addon disables death drops by players in active matches
