# Auto respawns players when they die
AutoRespawn:
  Enabled: true
  Delay: 0 # seconds

FriendlyFire: false

# Number of deaths one team much reach before they win
# A death only counts if the kill was from another player
# unless, they died from bleeding.
DeathThreshold: 30

# Max match duration in seconds
# Zero for unlimited duration
MaxDuration: 600

# Grace period after spawning in seconds
GracePeriod: 2

Loadouts:
- Title: Red
  Items:
  - Id: Viper
  - Id: Viper Magazine
    Amount: 4
  - Id: Red Shirt
- Title: Blue
  Items:
  - Id: Viper
  - Id: Viper Magazine
    Amount: 4
  - Id: Blue Shirt

Rewards:
  # Minimum number of total players needed to gain rewards
  # This is to stop players boosting and gaining massive
  # amounts of rewards when player count is low
  MinimumPlayers: 8

  Winners: # Only winners will receive these rewards
  - Id: Grilled Cheese Sandwich
    Amount: 1
    Chance: 1 # Represents a 100% chance
  - Id: Canned Beans
    Amount: 2
    # No defined chance also represents a 100% chance
  - Id: Eaglefire
    Amount: 1
    Chance: 0.1 # Represents a 10% chance
  Losers: # Only losers will receive these rewards
  - Id: Tomato
    Amount: 5
  Tied: # If the game comes to a tie, both teams will receive these rewards
  - Id: Grilled Cheese Sandwich
    Amount: 2
  All: # Both teams will receive these rewards in all cases
  - Id: Police Vest
    Amount: 1